# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aWnE_gm7SM634jt4SCI-G-xyJTAGvs9
"""

# !pip install -U datasets

import json
from transformers import AutoTokenizer
from datasets import Dataset
from torch.utils.data import DataLoader
from transformers import AutoModelForTokenClassification
import torch
from torch.optim import AdamW
from transformers import TrainingArguments
from transformers import DataCollatorForTokenClassification
import numpy as np
from sklearn.metrics import f1_score
from transformers import Trainer


"""### Loading subset of data"""

samples = []

with open("train_indicqa.jsonl", "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        samples.append(json.loads(line))
        if i == 31:   # first 32 samples
            break

dataset = Dataset.from_list(samples)

print(dataset)

"""## LOad Tokenizer"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-large")

MAX_LENGTH = 512

"""## Align Labels"""

def tokenize_and_align_labels(examples):

    # Pre-tokenize questions into words as expected by is_split_into_words=True
    processed_questions = [q.split() for q in examples["question"]]

    tokenized_inputs = tokenizer(
        processed_questions, # Pass the word-split questions
        examples["tokens"],
        truncation="only_second",
        max_length=MAX_LENGTH,
        padding="max_length",
        is_split_into_words=True,
    )

    all_labels = []

    for i, labels in enumerate(examples["labels"]):

        word_ids = tokenized_inputs.word_ids(batch_index=i)
        sequence_ids = tokenized_inputs.sequence_ids(batch_index=i)

        previous_word = None
        label_ids = []

        for word_id, seq_id in zip(word_ids, sequence_ids):

            # Special tokens
            if word_id is None:
                label_ids.append(-100)

            # Question tokens
            elif seq_id == 0:
                label_ids.append(-100)

            # First subword of each context token
            elif word_id != previous_word:
                label_ids.append(labels[word_id])

            # Remaining subwords
            else:
                label_ids.append(-100)

            previous_word = word_id

        all_labels.append(label_ids)

    tokenized_inputs["labels"] = all_labels

    return tokenized_inputs

tokenized_dataset = dataset.map(
    tokenize_and_align_labels,
    batched=True,
    remove_columns=dataset.column_names
)

tokenized_dataset.set_format(
    type="torch",
    columns=[
        "input_ids",
        "attention_mask",
        "labels"
    ]
)

"""## Data Loader

"""

train_loader = DataLoader(
    tokenized_dataset,
    batch_size=4,
    shuffle=True
)

model = AutoModelForTokenClassification.from_pretrained(
    "xlm-roberta-large",
    num_labels=2
)

batch = next(iter(train_loader))

print(batch["input_ids"].shape)
print(batch["attention_mask"].shape)
print(batch["labels"].shape)

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=10,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,

    learning_rate=2e-5,
    weight_decay=0.01,

    logging_steps=1,
    eval_strategy="epoch",
    save_strategy="no",

    report_to="none",
)



def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    true_labels = []
    true_predictions = []

    for prediction, label in zip(predictions, labels):

        for p, l in zip(prediction, label):

            if l != -100:

                true_labels.append(l)
                true_predictions.append(p)

    return {
        "f1": f1_score(true_labels, true_predictions)
    }

data_collator = DataCollatorForTokenClassification(tokenizer)


trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_dataset,
    eval_dataset=tokenized_dataset,

    data_collator=data_collator,

    compute_metrics=compute_metrics,
)
trainer.train()

pred = trainer.predict(tokenized_dataset)

logits = pred.predictions
labels = pred.label_ids

predictions = np.argmax(logits, axis=-1)

valid_preds = []
valid_labels = []

for p, l in zip(predictions, labels):
    mask = l != -100
    valid_preds.extend(p[mask])
    valid_labels.extend(l[mask])

print("Unique predictions:", np.unique(valid_preds, return_counts=True))
print("Unique labels:", np.unique(valid_labels, return_counts=True))

def predict(sample):
    model.eval()

    # Tokenize question and context
    encoding = tokenizer(
        sample["question"].split(),
        sample["tokens"],
        is_split_into_words=True,
        truncation="only_second",
        max_length=512,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids(batch_index=0)
    sequence_ids = encoding.sequence_ids(batch_index=0)

    encoding = {k: v.to(device) for k, v in encoding.items()}

    # Model prediction
    with torch.no_grad():
        outputs = model(**encoding)

    pred_labels = outputs.logits.argmax(dim=-1).squeeze().cpu().tolist()

    # Convert predictions back to original tokens
    compressed_tokens = []
    previous_word = None

    for pred, word_id, seq_id in zip(pred_labels, word_ids, sequence_ids):

        # Skip special tokens
        if word_id is None:
            continue

        # Skip question tokens
        if seq_id != 1:
            continue

        # Keep only first subword
        if word_id == previous_word:
            continue

        if pred == 1:
            compressed_tokens.append(sample["tokens"][word_id])

        previous_word = word_id

    return " ".join(compressed_tokens)

sample = dataset[0]

print("=" * 100)
print("QUESTION:")
print(sample["question"])

print("\nANSWER:")
print(sample["original_answer"])

print("Original Context")
print(" ".join(sample['tokens'])) # Fixed: call join on the separator string

print("\nMODEL Context:")
print(predict(sample))

