[project]
name = "group-9-ds-and-ai-lab-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "fastapi",
    "fsspec==2026.6.0",
    "gradio-client>=2.6.0",
    "numpy",
    "openai",
    "pydantic",
    "python-dotenv",
    "scikit-learn",
    "torch",
    "transformers",
    "uvicorn[standard]",
]

